### ISSUE TITLE
[INCOMPATIBILITY] Matrix anticheat

### ISSUE THREAD

**Issue by AMDBartek** [ViaVersion/ViaRewind#201]
The arm animation packet gets delayed and causes a FastBreak false positive. See https://github.com/jiangdashao/Matrix-Issues/issues/1975. Can provide more info if required.

**Comment by Gerrygames** [comment]
The 1.8 client sends the arm swing packet before the entity attack packet when attacking an entity. This results in the hit not doing any damage because the arm swing packet sets the weapon cooldown. There is no better solution to this as delaying the packet. Already discussed this issue extensively with konsolas.
