### ISSUE TITLE
1.8 client kick when newer version fallingblocks are spawned

### ISSUE THREAD

**Issue by PhanaticD** [ViaVersion/ViaRewind#305]
**Describe the bug, provide any errors**
basically the title

**How can we reproduce it?**
in my case use 1.8.9 client on a 1.15.2 server and spawn falling blocks of end bricks

**Expected behaviour**
no kick

**Screenshots**
https://streamable.com/2fg7r4 (zurina is the player on the 1.8 client)
https://cdn.discordapp.com/attachments/216678365766090752/831276579996172388/image0.png

**ViaVersion Dump:**
https://dump.viaversion.com/94b3eabeda228edaf1e98b97dcd85f65e8e80a2d13489eadf4f336f2c43dace5

**Additional server info**
I use waterfall for proxy

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [x] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by FlorianMichael** [comment]
Hi, I tried out multiple falling blocks but I can't get to reproduce the issue on latest Via* plugins:
![image](https://github.com/ViaVersion/ViaRewind/assets/60033407/d5136c55-9b06-442a-ba7c-8c397113e23f)

Also the links are not working so I can't read the kick message either, I just guess it's a plugin issue or something which got fixed in the meantime.
