### ISSUE TITLE
1.8 Client with Optifine invisible 

### ISSUE THREAD

**Issue by ludgart** [ViaVersion/ViaRewind#314]
### '/viaversion dump' Output

 https://dump.viaversion.com/1aa16d93035d6187525956f4199e7dd01183324fc908c7a1aa963548594b938c

### Console Error

No errors in the console

### Bug Description

See "Steps to Reproduce"

### Steps to Reproduce

Login with 1.8 with optifine installed (example forge or lunar)
Join the 1.16.5 server with ViaVersion-4.0.0-21w19a, ViaRewind-2.0.0 and ViaBackwards-4.0.0-21w19a
Die from a player
Respawn
NPC, Players and your self are invisible now (it look like that : https://media.discordapp.net/attachments/767315429189222450/843864694989258772/Screenshot_6.png?width=1791&height=875 )
Reconnecting doesnt help. Only a server restart help.

### Expected Behavior

No visible bug

### Additional Server Info

Proxy: Flamecore without any protocol plugin
Server: Paper-1.16.5 - 629
Java 13 (and java 15 tested)

Filtered sent packets https://pastebin.com/BFsM2mBB
It happen only for the player: Betman1234 ( bc of the client )

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by ludgart** [comment]
Need to update my issue. It doesnt matter if forge or not. It happen to a lot of players. Example Lunar client. I think, because of optifine, because if we remove optifine from forge it work without problems.

**Comment by Xernium** [comment]
As you’ve undoubtedly recognized- Optifine is the issue here. This issue has been brought up multiple times and it’s not something we will look into further as it works with vanilla or I modified clients.

**Comment by ludgart** [comment]
Wow, I'm disappointed. Why this project still exists? I switched to ViaVersion-3.2.1, ViaRewind-1.5.3 and ViaBackwards-3.2.0 and the bug is gone. But in this version is a other problem what I already reported it without success.

**Comment by Xernium** [comment]
As I said- ViaVersion is made to support **Vanilla** or unmodified clients. If modifications break that then we won’t help. That’s always been the deal, we can’t make it right for everyone. Besides that, 1.8 is quite a few years out of date now and rarely anyone still contributes code to maintaining these legacy versions. We chose to keep the older versions around because if we didn’t that would just spark another project to add them back. We compromised on not fixing bugs ourselves anymore associated with legacy versions more or less- But we are still taking in contributions by the community for maintenance of these versions.

**Comment by ludgart** [comment]
I'm pretty sure you know that the most Minecraft players use the "Mod" optifine. You guys have more experience to figure the problem out. I only can say it work with 3.2.1. There was a change what break it. I'm on your side, but in this case it breaks the gameplay immensely

**Comment by Earthcomputer** [comment]
Lol, imagine using quotation marks to call optifine a mod, it's a mod, and a pretty intrusive one at that, constantly breaking other mods.

**Comment by ludgart** [comment]
Oke, I found it. This version patch the invisible bug https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/238/.

**Plugin version list:**
ViaRewind-1.5.4-185 | vv  Build-392  | vbackward Build-237 | work
ViaRewind-1.5.4-185 | vv  Build-392  | vbackward Build-238 | failed

Can someone look over this? Better would be a new branch with reverse of these changes to test it again.

**Comment by KennyTV** [comment]
The commits from that build basically restore Vanilla behavior for respawns (which was previously broken for respawns in the same world for skin changers for example), so that's 100% on OptiFine - nothing we can fix, sorry. I'd suggest downgrading OptiFine to an earlier version.

**Comment by ludgart** [comment]
Wow, it took me hours to find the broken commits. It's not a solution for the players. A setting to restore the old behavior would be the best. But I see, reporting issues to improve the project is pointless. Second example https://github.com/ViaVersion/ViaRewind/issues/280. I think I need to create a fork of the project. You guys can "fix" it in 10 minutes and I need hours for it. Perfect.

**Comment by Camotoy** [comment]
Reporting issues to a project is not pointless. Reporting issues that *only* occur with clients that deviate from vanilla behavior is low priority or ignorable - if the mod breaks and not vanilla, it's probably the mod's fault, and not ViaVersion's.

**Comment by ludgart** [comment]
> See #280 and a other issue, but i forgot the number
> 
> Reporting issues to a project is not pointless. Reporting issues that _only_ occur with clients that deviate from vanilla behavior is low priority or ignorable - if the mod breaks and not vanilla, it's probably the mod's fault, and not ViaVersion's.

**Comment by KennyTV** [comment]
^ and as I said, the commits *restore Vanilla behavior* and will otherwise break a good number of plugins... including the Vanilla client. Either you choose a different OptiFine version (which I am almost certain will fix it), or you have to report broken respawn packet handling to OF, assuming you are using its latest version. The other issue you linked is due to Vanilla restrictions of older clients, and PS works in some cases - in others it doesn't (also considering PS works *completely* differently to Via internally and is based on a different concept of packet transformation).

In any case, you should drop the attitude if you have no idea of the client's inner workings and also drop the expectation of version translation to an 8 year old version to work flawlessly *in all possible scenarios* - that's plain and simply unrealistic.
