### ISSUE TITLE
Holograms falling in void on 1.7 Client causes a Witch to appear at Hologram location

### ISSUE THREAD

**Issue by Phirion** [ViaVersion/ViaRewind#425]
### `/viaversion dump` Output

https://dump.viaversion.com/9dd1656c41969a8b770ebb290a331d5d8767eae4d4acbbf1cd67fe381e99958e

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

When 1.7 users connect to a 1.8 server they will see all Holograms fall in the void which causes a witch to appear on the Hologram location.

For 1.8 users Holograms appear normal like they suppose to appear.

### Steps to Reproduce

1. Login on 1.7.10 on 1.8 server.
2. Have Holograms created using the HolographicDisplays plugin.
3. See how they fall in the void regardless where you have placed them.

### Expected Behavior

The Holograms should be displayed as how they do on 1.8+ without falling into void.

### Additional Server Info

I don't use BungeeCord on my server.

I've tested this on a localhost with ViaVersions,Viarewind and the HolographicDisplays plugins but this still causes the issue to appear.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: 1.8.8--R0.2--SNAPSHOT%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-1.8.8--R0.2--SNAPSHOT%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by c0dingnoobi** [comment]
#413 :/

**Comment by c0dingnoobi** [comment]
I had this issue since months. I went through all latest commits recently. e6b8b6937ebd80dcbeaa8670fc960b3d4164baf6 was the last comit where everything worked perfectly.
since 49067f8f06cd0a41ac1afe463125c81541a7c69f 1.7 players get kicked whenever holograms unloads/reloads (either when reloading through command or walking out of hologram range) with this [error](https://pastebin.com/gED2C15c) (which seems to be related to the entity destruction)
after the next commit 9e4ac93f10158c7bfa7c56f0d49a16a757e9037d this problem occured. neither does it print a stacktrace nor does it kick the client. 
as op described the hologram just falls into void and a witch spawns there

**Comment by c0dingnoobi** [comment]
Feel free to use my [fork](https://github.com/c0dingnoobi/ViaRewind/actions/runs/4146772778) @Phirion
